/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui_001;

import java.awt.Color; //Libreria para colores 
import javax.swing.JOptionPane; //Libreria para mostrar alertas en Java
import java.util.Calendar; //Clase para trabajar con fecha y hora
import java.text.SimpleDateFormat;  //Para simplificar como saca la fecha y hora, de lo contrario sale un relajo, ver ☺

/**
 *
 * @author Daniel
 */


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta1 = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        botonPrueba = new javax.swing.JButton();
        etiqueta2 = new javax.swing.JLabel();
        etiqueta3 = new javax.swing.JLabel();
        botonFecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOSE DANIEL MEJIA 20212030242");
        setBackground(new java.awt.Color(204, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        etiqueta1.setBackground(new java.awt.Color(51, 255, 0));
        etiqueta1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        etiqueta1.setForeground(new java.awt.Color(0, 0, 0));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Label de Tal");
        etiqueta1.setToolTipText("SOY UN LABEL ");
        etiqueta1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        etiqueta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiqueta1.setOpaque(true);

        boton1.setBackground(new java.awt.Color(255, 51, 0));
        boton1.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        boton1.setForeground(new java.awt.Color(102, 255, 153));
        boton1.setText("BOTON ");
        boton1.setToolTipText("presiona para cambiar color");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        botonPrueba.setBackground(new java.awt.Color(0, 255, 204));
        botonPrueba.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        botonPrueba.setForeground(new java.awt.Color(0, 0, 0));
        botonPrueba.setText("Boton 2");
        botonPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPruebaActionPerformed(evt);
            }
        });

        etiqueta2.setBackground(new java.awt.Color(75, 242, 33));
        etiqueta2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        etiqueta2.setForeground(new java.awt.Color(0, 0, 0));
        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta2.setText("etiqueta2");
        etiqueta2.setOpaque(true);

        etiqueta3.setBackground(new java.awt.Color(51, 255, 0));
        etiqueta3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        etiqueta3.setForeground(new java.awt.Color(0, 0, 0));
        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta3.setText("Label de Tal");
        etiqueta3.setToolTipText("SOY UN LABEL ");
        etiqueta3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        etiqueta3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiqueta3.setOpaque(true);

        botonFecha.setBackground(new java.awt.Color(0, 255, 204));
        botonFecha.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        botonFecha.setForeground(new java.awt.Color(0, 0, 0));
        botonFecha.setText("Boton 2");
        botonFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(botonFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(botonPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiqueta3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(etiqueta3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(botonFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        
        //Cuando se haga click al boton se ejecuta lo que este aca
        
        //MOSTRAR UNA ALERTA EN PANTALLA CON UN TEXTO
        this.getContentPane().setBackground(Color.blue);
        JOptionPane.showMessageDialog(this, "Hola soy una alerta");  //Esto es para la ALERTA
        etiqueta1.setText("Nuevo texto");
        
        
        
    }//GEN-LAST:event_boton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //forzar la app del color de fondo seleccionado (backgroundColor)
        this.getContentPane().setBackground(this.getBackground());
    }//GEN-LAST:event_formWindowOpened

    private void botonPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPruebaActionPerformed
       /*Ejericio, al hacr click en botonPrueba mostrar primernombre en etiqueta2
        Luego mostrar un JOPTIONPANE con primer apellido*/
        
        etiqueta2.setText("Jose");
        JOptionPane.showMessageDialog(this, "Mejia");
        
    }//GEN-LAST:event_botonPruebaActionPerformed

    private void botonFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFechaActionPerformed
        //Crear un objeto basado en CALENDAR
        Calendar fecha = Calendar.getInstance();
        //Convertir fecha en algo maslegible usando Simple date format
        SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd HH:mm:ss");
        
        //Imprimirlo en el etiqueta 3
        etiqueta3.setText(formato.format(fecha.getTime()));//☺
        
        
    }//GEN-LAST:event_botonFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton botonFecha;
    private javax.swing.JButton botonPrueba;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiqueta3;
    // End of variables declaration//GEN-END:variables
}
